#!/bin/sh

################################################################################
# Copyright (c) 2022 ModalAI, Inc. All rights reserved.
#
# author: james@modalai.com
################################################################################

echo ""
echo "Done installing voxl-mpa-to-ros"
echo ""